/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package factory;

import Windows.FrameIcons;
import Windows.WindowsStyle;

/**
 *
 * @author andy737-1
 */
public class OperationViewer extends javax.swing.JFrame {

    private String operaciones;
    private CollectorGUI gui;
    private Boolean exit;

    /**
     * Creates new form OperationViewer
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public OperationViewer(CollectorGUI gui) {
        WindowsStyle ws = new WindowsStyle();
        FrameIcons ic = new FrameIcons();
        ws.SetStyle();
        ic.SetIcon();
        this.setIconImages(ic.GetIcon());
        initComponents();
        this.setLocationRelativeTo(null);
        operaciones = "";
        this.gui = gui;
        exit = false;
    }

    public void setText(String operaciones) {
        this.operaciones = operaciones;
    }

    public void setExit(Boolean exit) {
        this.exit = exit;
    }

    public void Append() {
        txtaOperaciones.append(operaciones);
        txtaOperaciones.setCaretPosition(txtaOperaciones.getText().length());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtaOperaciones = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Procesando archivos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtaOperaciones.setBackground(new java.awt.Color(0, 0, 0));
        txtaOperaciones.setColumns(20);
        txtaOperaciones.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtaOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        txtaOperaciones.setLineWrap(true);
        txtaOperaciones.setRows(5);
        txtaOperaciones.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtaOperaciones.setEnabled(false);
        jScrollPane2.setViewportView(txtaOperaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (exit) {
            this.dispose();
            gui.setVisible(true);
        }

    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtaOperaciones;
    // End of variables declaration//GEN-END:variables
}
